version: "3.8"
services:
  app:
    container_name: forum
    build:
      context: .
      args:
        USER: docker
        UID: 1000
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql
    working_dir: /usr/src/app
    environment:
      SERVICE_NAME: app
    networks:
      - network

  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx/.
    volumes:
      - "./public:/usr/src/app/public"
    environment:
      NGINX_FPM_HOST: app
      NGINX_ROOT: /usr/src/app/public
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - network

  mysql:
    container_name: mysql
    build:
      context: ./docker/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - "./.docker/mysql:/var/lib/mysql"
    networks:
      - network

  phpmyadmin:
    container_name: phpmyadmin
    build: ./docker/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_USERNAME}
      - MYSQL_ROOT_PASSWORD=${DB_USERNAME}
    ports:
      - "8000:80"
    depends_on:
      - mysql
    networks:
      - network

networks:
  network:
    driver: bridge
